VeeamHub/veeam-ansible

galaxy.yml, roles/veeam_vas/README.md, roles/veeam_vas/meta/main.yml
Updated supported Ansible version from 2.8+ to 2.9+. Ansible Galaxy doesn't support installing Collections using 2.8.
This was tested and verified in a lab environment.
=> Updating supported Ansible version

galaxy.yml
Breaking change by Ansible Galaxy mandates that both `license` and `license_file` metadata entries cannot be used in conjunction.
I removed `license` as I'd rather the LICENSE file in the project itself be the determining factor.
=> Updating Ansible Galaxy Config

galaxy.yml, roles/veeam_vas/vars/em_v10.yml, roles/veeam_vas/vars/one_v10.yml, roles/veeam_vas/vars/vbr_v10.yml
* Updated ISO URLs and Checksums
* VBR
* EM
* ONE
Tested deployment for VBR, EM, and ONE in my lab successfully.
=> Updating for 10a

galaxy.yml, roles/veeam_vas/tasks/em_upgrade.yml, roles/veeam_vas/tasks/one_agent_upgrade.yml, roles/veeam_vas/tasks/one_client_upgrade.yml, roles/veeam_vas/tasks/one_server_upgrade.yml, roles/veeam_vas/tasks/one_web_ui_upgrade.yml, roles/veeam_vas/tasks/vbr_upgrade.yml
This was originally put into place to stop upgrades early on if the source version was an unsupported upgrade. A problem with this design was exposed VBR 10a as it was released as a full ISO vs a patch file.
A full ISO uses the upgrade process to apply updates so we can no longer assume that upgrades will occur from the previous version of the product.
To resolve this behavior, I'm removing the source version verification checks. This should not be an issue as the software upgrade itself has these checks built-in.
Code has been tested in my lab.
=> Removing upgrade checks

galaxy.yml, plugins/modules/pending_reboot_check.ps1, plugins/modules/pending_reboot_check.py, roles/veeam_vas/tasks/em_install.yml, roles/veeam_vas/tasks/em_upgrade.yml, roles/veeam_vas/tasks/vbr_install.yml, roles/veeam_vas/tasks/vbr_upgrade.yml
If a pending reboot flag is present prior to performing a Veeam Install/Upgrade, it can cause failures in the automation.
* Added a pending reboot check to the pretask list of the following:
* EM install
* EM upgrade
* VBR install
* VBR upgrade
* Added a pending reboot check to the post-task list of the following:
* EM install
* VBR install
* While the post-check isn't required from a Veeam standpoint, it's good practice.
Tested in a lab environment.
=> Added Pending Reboot check

galaxy.yml, roles/veeam_vas/tasks/em_install.yml, roles/veeam_vas/tasks/vbr_install.yml
Added a message for more descriptive reboots
Tested in lab.
=> Added reboot message

.gitignore, galaxy.yml, plugins/modules/pending_reboot_check.py, roles/veeam_vas/README.md, roles/veeam_vas/tasks/em_install.yml, roles/veeam_vas/tasks/em_patch.yml, roles/veeam_vas/tasks/em_upgrade.yml, roles/veeam_vas/tasks/install_net_framework.yml, roles/veeam_vas/tasks/mount_iso.yml, roles/veeam_vas/tasks/one_agent_install.yml, roles/veeam_vas/tasks/one_agent_upgrade.yml, roles/veeam_vas/tasks/one_client_install.yml, roles/veeam_vas/tasks/one_client_upgrade.yml, roles/veeam_vas/tasks/one_install_pretasks.yml, roles/veeam_vas/tasks/one_patch.yml, roles/veeam_vas/tasks/one_server_install.yml, roles/veeam_vas/tasks/one_server_upgrade.yml, roles/veeam_vas/tasks/one_web_ui_install.yml, roles/veeam_vas/tasks/one_web_ui_upgrade.yml, roles/veeam_vas/tasks/vbr_install.yml, roles/veeam_vas/tasks/vbr_install_pretasks.yml, roles/veeam_vas/tasks/vbr_patch.yml, roles/veeam_vas/tasks/vbr_upgrade.yml
- Ansible 2.10 moved previously builtin modules to the newer collections
- Updated modules to reflect this change
- Updated documentation showing the new collection dependencies
- Tested all changes in lab
- Incremented collection version
Fixes #9 
Tested in my lab.
=> Adding support for Ansible 2.10.x

.ansible-lint, .github/workflows/ansible-lint.yml, roles/veeam_vas/tasks/em_install.yml, roles/veeam_vas/tasks/em_upgrade.yml, roles/veeam_vas/tasks/one_server_install.yml, roles/veeam_vas/tasks/one_server_upgrade.yml, roles/veeam_vas/tasks/vbr_install.yml, roles/veeam_vas/tasks/vbr_install_pretasks.yml, roles/veeam_vas/tasks/vbr_upgrade.yml
This PR is to improve automated syntax checking using `ansible-lint`.
- Adding ansible-lint as a workflow in GH Actions
- Workflow will run on every push/pull request
- Fixed syntax issues brought up by ansible-lint
- Added .ansible-lint config file to standardize proper lint setting
This code was tested & validated in another GitHub repository.
=> Adding ansible-lint workflow

galaxy.yml, plugins/modules/veeam_vbr_cloud_connect_maintenance.ps1, plugins/modules/veeam_vbr_config_backup.ps1, plugins/modules/veeam_vbr_upgrade_job_prep.ps1, roles/veeam_vas/README.md, roles/veeam_vas/defaults/main.yml, roles/veeam_vas/tasks/em_install.yml, roles/veeam_vas/tasks/em_patch.yml, roles/veeam_vas/tasks/em_upgrade.yml, roles/veeam_vas/tasks/install_net_framework.yml, roles/veeam_vas/tasks/mount_iso.yml, roles/veeam_vas/tasks/one_agent_install.yml, roles/veeam_vas/tasks/one_agent_upgrade.yml, roles/veeam_vas/tasks/one_client_install.yml, roles/veeam_vas/tasks/one_client_upgrade.yml, roles/veeam_vas/tasks/one_install_pretasks.yml, roles/veeam_vas/tasks/one_patch.yml, roles/veeam_vas/tasks/one_server_install.yml, roles/veeam_vas/tasks/one_server_upgrade.yml, roles/veeam_vas/tasks/one_web_ui_install.yml, roles/veeam_vas/tasks/one_web_ui_upgrade.yml, roles/veeam_vas/tasks/vbr_install.yml, roles/veeam_vas/tasks/vbr_install_pretasks.yml, roles/veeam_vas/tasks/vbr_patch.yml, roles/veeam_vas/tasks/vbr_upgrade.yml, roles/veeam_vas/vars/em_v11.yml, roles/veeam_vas/vars/one_v11.yml, roles/veeam_vas/vars/vbr_v11.yml
This PR includes all necessary code for this collection to work with the Veeam Availability Suite (VBR,EM,ONE).
Fixes #10 
This has been tested in my lab across multiple deployment scenarios including the following:
* Local DB (SQL Express)
* Remote DB (MS SQL)
* VBR & EM on same/separate servers
* Standard & Cloud Connect environments
* Install/Upgrade
* Tested with both v10/v11
* Local DB (SQL Express)
* Remote DB (MS SQL)
* Typical/Advanced deployments
* Install/Upgrade
* Tested with both v10/v11
=> V11 update

galaxy.yml, roles/veeam_vas/defaults/main.yml, roles/veeam_vas/tasks/mount_iso.yml, roles/veeam_vas/tasks/vbr_install.yml, roles/veeam_vas/tasks/vbr_upgrade.yml
- Added check to skip ISO version validation
- This is a debugging function and meant to be used in testing scenarios where a predefined variable file doesn't exist.
- i.e. Beta testing
- Adding new software requirements
- Microsoft .NET Core Runtime
- Microsoft ASP.NET Core Shared Framework
- These packages are not required by EM
- Adding Explorer for MS Teams
- Added installer for Veeam Explorer for Microsoft Teams
Tested new code in my lab installing & upgrading to v10 & v11.
=> Add new v11 packages

galaxy.yml, roles/veeam_vas/vars/em_v11.yml, roles/veeam_vas/vars/vbr_v11.yml
Updated v11 EM/VBR var files with the latest ISO and corresponding ISO checksum.
Tested in lab for a successfully v11 installation/upgrade using the new ISO.
=> Updated to most recent ISO

galaxy.yml, roles/veeam_vas/vars/one_v11.yml
Updated `one_v11.yml` to the latest ISO URL and checksum.
Tested new ISO in my lab successfully with multiple install scenarios.
=> Updated to latest ISO

.github/workflows/ansible-lint.yml, galaxy.yml, roles/veeam_vas/vars/em_v11.yml, roles/veeam_vas/vars/one_v11.yml, roles/veeam_vas/vars/vbr_v11.yml
Updated the following products:
- Veeam ONE v11
- Veeam Backup & Replication v11
- Veeam Backup Enterprise Manager v11
I tested deployments of each updated ISO successfully in a lab environment.
=> Updating ISO URLs to latest

galaxy.yml, roles/veeam_vas/tasks/one_install_pretasks.yml, roles/veeam_vas/tasks/one_server_upgrade.yml, roles/veeam_vas/tasks/vbr_install.yml, roles/veeam_vas/tasks/vbr_upgrade.yml
- Veeam ONE updates
- Updated code to handle newer versions of software dependencies while
maintaining support for older versions.
- Added logging for MS Visual C++ Redistributable install
- Updated logic so that upgrade can proceed even if Veeam services are already stopped
- Added step to start Veeam services after upgrade is complete.
- VBR updates
- Updated code to handle newer versions of software dependencies while
maintaining support for older versions.
- Added MS Visual C++ Redistributable install for both installs/upgrades
- Added Veeam Agent for Unix Redistributable install
- Updating collection dependencies to latest versions
- ansible.windows: '1.7.3'
- …
=> 11a updates

meta/runtime.yml
Added new file required in Ansible collections. It let's Ansible Galaxy know supported Ansible versions.
Fixes #22
=> New Ansible Collection Reqirements

galaxy.yml, roles/veeam_vas/README.md
* updating playbook sample for local postgres install mentioned in issue #38
* incrementing galaxy version number
This was only a documentation update so no testing was performed.
=> Updating sample playbooks

galaxy.yml, roles/veeam_vas/README.md, roles/veeam_vas/tasks/vbr_patch.yml, roles/veeam_vas/vars/em_v12.yml, roles/veeam_vas/vars/vbr_v12.yml
* Updating VBR/EM ISO to the latest version
* Improved VBR patch post-install logic to skip unnecessary actions
* Fixed typo in documentation
Changes were tested and confirmed working in a lab environment.
=> Updating ISO to latest version

galaxy.yml, meta/runtime.yml, roles/veeam_vas/README.md, roles/veeam_vas/meta/main.yml
Ansible version needs to be at least 2.12 to support dependent collection ansible.windows.
Updated metadata and documentation to show correct ansible version.
Fixes #41 
Change was tested in a lab environment.
=> Updated minimum Ansible version

.gitignore
Simple Update of the gitignore file for Ansible pyCache
=> Ansible Ignore

.github/workflows/deploy-collection.yml
Switched to a new workflow for deploying this collection to Ansible Galaxy.
Fixes #61
=> Updating workflow to deploy collection to Ansible Galaxy

CHANGELOG.rst, galaxy.yml, roles/veeam_vas/tasks/one_install_pretasks.yml, roles/veeam_vas/vars/one_v12.yml
Fixes #65
Fixes #66
Incremented galaxy version
Updated CHANGELOG
Tested successfully in a lab environment.
=> Fixing ONE installation bugs

CHANGELOG.rst, galaxy.yml, roles/veeam_vas/README.md, roles/veeam_vas/tasks/em_install.yml, roles/veeam_vas/tasks/vbr_install.yml, roles/veeam_vas/vars/em_v12.yml, roles/veeam_vas/vars/vbr_v12.yml
Updated VBR/EM ISO to the latest version. Fixed multiple minor bugs.
Fixes #64 
Fixes #68 
Fixes #69 
Tested in a lab environment.
=> Update vbr iso 07262024
